### ISSUE TITLE
Cannot Find Module dart_sdk

### ISSUE THREAD

**Issue by SupposedlySam** [pulyaevskiy/firebase-functions-interop#76]
When generating the `index.dart.js` and `index.dart.bootstrap.js` files using `pub run build_runner build -o node:build` the `dart_sdk` is specified as a module under the path "packages/$sdk/dev_compiler/common/dart_sdk". 

However, when attempting to run `firebase emulators:start --only functions`, I get the following error:
```
Error: Cannot find module '/Users/supposedlysam/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/lib/emulator/packages/$sdk/dev_compiler/common/dart_sdk'
Require stack:
- /Users/supposedlysam/development/flyby/functions/build/index.dart.bootstrap.js
- /Users/supposedlysam/development/flyby/functions/build/index.dart.js
- /Users/supposedlysam/.nvm/versions/node/v15.14.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at Module.require (/Users/supposedlysam/development/flyby/functions/build/index.dart.bootstrap.js:52:24)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/supposedlysam/development/flyby/functions/build/index.dart.bootstrap.js:57:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

Has the `dart_sdk` been removed or relocated?

**Comment by SupposedlySam** [comment]
This error ended up being with the `build_node_compilers` package. I needed to update my `build.yaml` file to use the dart2js compiler instead. (Note: the build.yaml file also needed to be inside of the `functions` folder as well)

#### build.yaml
```yaml
targets:
  $default:
    sources:
      - node/**
      - lib/**
    builders:
      build_node_compilers|entrypoint:
        options:
          compiler: dart2js
```
